#!/usr/bin/env python3
"""生成済み記事を WordPress REST API に投稿するモジュール。

generate.py から呼ばれる。MD → HTML 変換 + Application Password 認証 + 投稿。
"""
from __future__ import annotations

import base64
import os
import re
import sys
from typing import Optional

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def md_to_html(md_text: str) -> str:
    """シンプルな MD→HTML 変換（依存ライブラリなし）。"""
    html = md_text

    # コードブロック退避
    code_blocks = []
    def stash_code(m):
        code_blocks.append(m.group(1))
        return f"\x00CODE{len(code_blocks)-1}\x00"
    html = re.sub(r"```[a-zA-Z0-9_+\-]*\n?(.*?)```", stash_code, html, flags=re.DOTALL)

    # 見出し
    html = re.sub(r"^#### (.+)$", r"<h4>\1</h4>", html, flags=re.MULTILINE)
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)

    # 強調
    html = re.sub(r"\*\*([^*\n]+)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"(?<![\*])\*([^*\n]+)\*(?![\*])", r"<em>\1</em>", html)

    # リンク
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', html)

    # リスト
    lines = html.split("\n")
    output = []
    in_ul = False
    for line in lines:
        m = re.match(r"^- (.+)$", line)
        if m:
            if not in_ul:
                output.append("<ul>")
                in_ul = True
            output.append(f"<li>{m.group(1)}</li>")
        else:
            if in_ul:
                output.append("</ul>")
                in_ul = False
            output.append(line)
    if in_ul:
        output.append("</ul>")
    html = "\n".join(output)

    # 段落
    paragraphs = []
    for chunk in re.split(r"\n\n+", html):
        chunk = chunk.strip()
        if not chunk:
            continue
        if chunk.startswith(("<h", "<ul", "<ol", "<blockquote", "<p", "<div")):
            paragraphs.append(chunk)
        else:
            chunk = chunk.replace("\n", "<br>\n")
            paragraphs.append(f"<p>{chunk}</p>")
    html = "\n\n".join(paragraphs)

    # コードブロック復元
    for i, code in enumerate(code_blocks):
        html = html.replace(f"\x00CODE{i}\x00", f"<pre><code>{code}</code></pre>")

    return html


def parse_md_article(md_text: str) -> dict:
    """frontmatter + body を分離。"""
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", md_text, re.DOTALL)
    if not m:
        return {"data": {}, "body": md_text}
    fm = m.group(1)
    body = m.group(2).strip()
    data = {}
    in_faq = False
    faq = []
    for line in fm.split("\n"):
        if re.match(r"^faq:\s*$", line):
            in_faq = True
            continue
        if in_faq:
            qm = re.match(r"^\s+- \[\"([^\"]+)\",\s*\"([^\"]+)\"\]\s*$", line)
            if qm:
                faq.append([qm.group(1), qm.group(2)])
                continue
            elif re.match(r"^[a-zA-Z]", line):
                in_faq = False
        kv = re.match(r'^([a-zA-Z_]+):\s*"?([^"]*)"?$', line)
        if kv:
            data[kv.group(1)] = kv.group(2).strip().strip('"')
    if faq:
        data["faq"] = faq
    return {"data": data, "body": body}


def build_jsonld_block(data: dict, wp_url: str) -> str:
    """記事用の schema.org JSON-LD を <script> ブロックで返す。"""
    base = {
        "@context": "https://schema.org",
        "@type": "MedicalWebPage",
        "headline": data.get("title", ""),
        "description": data.get("excerpt", ""),
        "datePublished": data.get("date", ""),
        "dateModified": data.get("date", ""),
    }
    blocks = [
        '<!-- schema.org JSON-LD (auto-generated by GAP-AIO) -->',
        f'<script type="application/ld+json">{__import__("json").dumps(base, ensure_ascii=False)}</script>',
    ]
    if data.get("faq") and isinstance(data["faq"], list):
        faq_jsonld = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": q,
                    "acceptedAnswer": {"@type": "Answer", "text": a},
                }
                for q, a in data["faq"]
            ],
        }
        blocks.append(
            f'<script type="application/ld+json">{__import__("json").dumps(faq_jsonld, ensure_ascii=False)}</script>'
        )
    return "\n".join(blocks)


def post_to_wordpress(md_text: str, wp_config: dict, verify_ssl: bool = False) -> dict:
    """WP REST API に記事を POST する。

    wp_config 必須: wp_url, wp_user, wp_app_pass
    任意: category_ids, status (draft/publish), featured_media
    """
    wp_url = wp_config.get("wp_url", "").rstrip("/")
    user = wp_config.get("wp_user", "")
    app_pass = wp_config.get("wp_app_pass", "")
    if not (wp_url and user and app_pass):
        raise ValueError("wp_url / wp_user / wp_app_pass required in client config")

    parsed = parse_md_article(md_text)
    data = parsed["data"]
    body = parsed["body"]

    html = md_to_html(body)
    jsonld = build_jsonld_block(data, wp_url)

    # FAQ をHTML本文末尾に追加（AIO引用しやすくするため）
    faq_html = ""
    if data.get("faq"):
        faq_html = '<h2>よくあるご質問</h2>\n'
        for q, a in data["faq"]:
            faq_html += f'<h3>Q. {q}</h3>\n<p>A. {a}</p>\n'

    full_content = html + "\n" + faq_html + "\n" + jsonld

    payload = {
        "title": data.get("title", "untitled"),
        "content": full_content,
        "status": wp_config.get("status", "draft"),
        "excerpt": data.get("excerpt", ""),
    }
    if wp_config.get("category_ids"):
        payload["categories"] = wp_config["category_ids"]
    if wp_config.get("featured_media"):
        payload["featured_media"] = wp_config["featured_media"]

    token = base64.b64encode(f"{user}:{app_pass}".encode()).decode()
    headers = {
        "Authorization": f"Basic {token}",
        "Content-Type": "application/json",
        "User-Agent": "gap-aio-engine/0.1",
        "Accept": "application/json",
    }

    api = f"{wp_url}/wp-json/wp/v2/posts"
    r = requests.post(api, json=payload, headers=headers, timeout=120, verify=verify_ssl)
    if r.status_code not in (200, 201):
        raise RuntimeError(f"WP POST failed {r.status_code}: {r.text[:600]}")
    res = r.json()
    return {
        "id": res["id"],
        "link": res.get("link"),
        "status": res.get("status"),
        "title": data.get("title"),
    }
